version: '3.9'
services:
  db:
    image: postgres:15
    container_name: orion-db
    environment:
      POSTGRES_USER: orion
      POSTGRES_PASSWORD: orion123
      POSTGRES_DB: orion_ledger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
